rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer_bank2
server:
  port: 56082
spring:
  application:
    name: dtx-txmsg-demo-bank2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bank2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root



